### ISSUE TITLE
Mochila preta nas costas do personagem

### ISSUE THREAD

**Issue by lucianoxplod** [DaniloRds/Base-Unity-Clean#1]
Primeiramente parabéns, a base está muito boa. O único problema que tive é que apareceu uma mochila preta nas costas do personagem que não consigo tirar. Se puder ajudar agradeço.

**Comment by DaniloRds** [comment]
Olá Luciano, você sabe o que você fez ou em qual lugar foi pra ela
aparecer? tenta ir na loja de roupas na parte de colete, mochilas ou
camisetas para remover.

Em seg., 6 de mar. de 2023 às 01:52, lucianoxplod ***@***.***>
escreveu:

**Comment by lucianoxplod** [comment]
> 

Ela apareceu do nada uma hora eu abre e o personagem estava com ela. Tinha tentado ir na parte de mochilas e não saia por nada. como você falou que poderia estar em outras categorias, eu fui tentando em todas, estava na parte de gravatas. consegui tirar. Obrigado pela ajuda. Parabéns novamente pelo projeto.

**Comment by DaniloRds** [comment]
Acontece, essas roupas ficam todas desorganizadas...

Muito obrigado pelo apoio, aos poucos vou postando atualizações, para ficar
por dentro delas entra no discord da loja.
Link: https://discord.gg/pbT5wVp8e9

Em seg., 6 de mar. de 2023 às 12:05, lucianoxplod ***@***.***>
escreveu:
